### ISSUE TITLE
Picture for Diamondback Explorer not appearing.

### ISSUE THREAD

**Issue by Dxnxsh** [Lasa2/ED-RichPresence#10]
Picture for Diamondback Explorer not appearing on discord status.
Maybe you forgot to add them to the art assets ?

![Capture](https://user-images.githubusercontent.com/37016152/69725943-5c361b00-115a-11ea-8869-c8beb4b23422.PNG)

**Comment by VeeLume** [comment]
Should be fixed, the asset had a wrong name
