### ISSUE TITLE
Fatal error on game load

### ISSUE THREAD

**Issue by mousebyte** [Lasa2/ED-RichPresence#11]
I'm getting a fatal error "Failed to execute script gui" when I load into the game.
Everything works fine up until that point, it detects that I'm in the launcher, and then detects that I'm in the main menu when I launch the game. It's only after I actually load my save that it crashes.

I used the logging.yaml file from issue #2 to retrieve a debug log:

[ed-rp.log](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/4137680/ed-rp.log)

It consistently fails on an "event checks" log entry each time. I've tried launching ED before Rich Presence and using the auto-launch option, the error happens either way.

**Comment by VeeLume** [comment]
Could you upload the Journal? Then i could recreate the issue on my side.

**Comment by mousebyte** [comment]
Sure, I'll repeat the process and upload my most recent journal.

**Comment by mousebyte** [comment]
Alright, here's my entire journal folder after the last attempt:

[journal.zip]() (removed as the issue is closed and the journals contained the FID)

**Comment by VeeLume** [comment]
Okay i found the issue and fixed it. There is a new release available.
