### ISSUE TITLE
Build Guide? Edit Strings in config?

### ISSUE THREAD

**Issue by spide-r** [Lasa2/ED-RichPresence#12]
First of all thank you for making this awesome RPC. 

I was wondering if you could write up a guide on how to build and compile a version ourselves? I wanted to fiddle around with it and possibly change some strings around, eg something like `CMDR Nathan flying Anaconda` when hovering over the ship icon. I feel like the stuff I want to do isn't worth a pull request, but I may be wrong.

It's alright if you don't feel it's worth it, still a great project!

**Comment by VeeLume** [comment]
I updated the readme to include a short description. Reopen the issue if there is something wrong with it.
