### ISSUE TITLE
Ship spelling errors

### ISSUE THREAD

**Issue by quaesn** [Lasa2/ED-RichPresence#15]
https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/blob/8073c2cf7fdb227d0385014de62c582048d6f663/watch.py#L210
There are a few ships with incorrect names or capitalization issues:
"ASP Explorer" should be "Asp Explorer"
"Ferderal Corvette" should be "Federal Corvette"
"Ferderal Gunship" should be "Federal Gunship"
"Ferderal Dropship" should be "Federal Dropship"
"Ferderal Assault Ship" should be "Federal Assault Ship"

I don't know how to edit or if I can even, I just made this account to point out these spelling errors.

**Comment by VeeLume** [comment]
Schould be fixed now
