### ISSUE TITLE
How to launch Steam Edition Launcher using EDRP

### ISSUE THREAD

**Issue by telumletiferum** [Lasa2/ED-RichPresence#19]
I know this might be a stupid question/issue that I have but I can't seem to find a solution anywhere on the internets so I came back here to ask if you guys might have an answer. So as the title of issue says, I can't figure out for the life of me, what launch arguments to use, in order for EDLaunch to use steam log in instead of the default frontier log in. I really would appreciate if you guys could help me out here.
P.S: Just to make clear, ED is purchased from Steam and you can launch it only through steam. If I try to launch through EDLaunch and login with my Frontier acc it tells me to buy the game.

**Comment by VeeLume** [comment]
It should be quite simple, all the app does is pass the path and arguments provided to the shell.
![image](https://user-images.githubusercontent.com/23563093/115994380-037ce300-a5d7-11eb-9a2d-a7a70de3f83a.png)
As path you take the path of your steam installation.
As arguments you use `-applaunch 359392`. The number is the steam app id that you can look up at https://steamdb.info/ -> https://steamdb.info/app/359320/ or you take the url from the steam store site https://store.steampowered.com/app/359320/Elite_Dangerous/.

With these settings it should work. Also i noticed that threre is a better way to wait for the launcher to continue and the delay option is not necessarily. So new release with that improvment!

**Comment by telumletiferum** [comment]
Still doesn't seem to work. When I use that config the app gives me a fatal error "Failed to execute script BackgroundApp", and the launcher does not appear. Now in my case the Steam installation and ED installation are on two separate drives. Could that be a problem or not?

**Comment by VeeLume** [comment]
Oh i forgot to mention there is a bug with the delay in the V4.0, so make sure to use the new release. If you already use the new release you could test if you can launch Elite through the commandline with the path and the arguments.
- win + r -> cmd -> enter
- then type the path + the arguments e.g. "C:/Program Files (x86)/Steam/Steam.exe" -applaunch 359320 -> enter
if that doesnt work then the path is probably wrong, else its my app and i need some time to set some proper logging up

And steam and ED being on two diffrents drives shouldnt be a problem as its the same for me

**Comment by telumletiferum** [comment]
Alright now there's no error, however having set everything up in the launcher, Path and arguments, now the app just stays there in the tray and doesn't launch the game. Launching the game through the cmd prompt is working.

**Comment by VeeLume** [comment]
Is the tray application unresposive or can you interact with rightclick with it?

**Comment by telumletiferum** [comment]
Unresponsive

**Comment by VeeLume** [comment]
Huh that is interesting. If you start the launcher yourself is the the rich presence working?

**Comment by telumletiferum** [comment]
Yes if I launch the game manually the RP works

**Comment by VeeLume** [comment]
Okay then i need to set some logging up, i can probably get to that in the next few days. So sorry that i cant help you currently

**Comment by telumletiferum** [comment]
No probs mate. The life of a dev is hard. By the way I gotta say that you've done a very good job with this project. I shall wait for the changes

**Comment by VeeLume** [comment]
Ive published a new release with logging. Just start it with the ED Launcher open, set the logging option to debug and restart the app. In the folder should then be a edrp.log file. Then reproduce the bug and upload the logfile

**Comment by telumletiferum** [comment]
Now it works on the latest release. Really strange it didn't work before since all you did was add some logging. Welp, I guess issue is fixed ¯\_(ツ)_/¯
