### ISSUE TITLE
"Failed to execute script BackgroundApp" Crash

### ISSUE THREAD

**Issue by LokeYourC3PH** [Lasa2/ED-RichPresence#20]
**Describe the bug**
What the title says, program crashes upon startup and then closes itself.

**Upload Journalfiles**
[Journal.210509213146.01.log](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6447515/Journal.210509213146.01.log)

![image](https://user-images.githubusercontent.com/5807595/117572665-d4a25900-b10e-11eb-8d81-8ddd66c41eb9.png)

That's it, hope you can solve it ^^

**Comment by VeeLume** [comment]
The Journal file works fine for me, so it crashes probably before. There should be a edrp.log file in the app directory, could you upload that too?

**Comment by LokeYourC3PH** [comment]
Gotcha. Here you go: 
[edrp.log](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6448961/edrp.log)

I can see nothing suspicious in that log file though, nothing hinting at any issues in it.

**Comment by VeeLume** [comment]
Based on the log i guess that the app was working at the first startup, then you changed a setting and since then it crashes? Could you upload your settings.yaml file?

**Comment by LokeYourC3PH** [comment]
That is correct, it did work the first time. Here my settings.yaml (I renamed the extension to .txt due to GitHub) : 

[settings.yaml.txt](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6455947/settings.yaml.txt)

**Comment by VeeLume** [comment]
Ive published a new release whith some improved logging, can you try to run that and upload the new log?

**Comment by LokeYourC3PH** [comment]
> 
> 
> Ive published a new release whith some improved logging, can you try to run that and upload the new log?

You forgot the release itself in that update you published, only source code was published ^^

**Comment by VeeLume** [comment]
sorry, i fixed it now

**Comment by LokeYourC3PH** [comment]
Yeah so it crashed again. What log do you want now?

[edrp.log](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6469885/edrp.log)
[Journal.210512220559.01.log](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6469887/Journal.210512220559.01.log)

**Comment by VeeLume** [comment]
Alright the bug is fixed, a new release is availabe.

**Comment by LokeYourC3PH** [comment]
![image](https://user-images.githubusercontent.com/5807595/118130684-9f607880-b438-11eb-83e0-1346c68b1f83.png)

Can confirm, bug fixed. Thanks a bunch!
