### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by thenamesjay03** [Lasa2/ED-RichPresence#23]
When I try to open it with or with out elite open i get a white box appear for less then a second then the application closes

**Comment by VeeLume** [comment]
There should be a file named settings.yaml, change the value of the line **log_level** to DEBUG while the application is closed. Then run the app while the launcher of Elite is open, after that please upload the edrp.log file (you can add .txt to upload it).

**Comment by thenamesjay03** [comment]
ok i changed the log level to debug and its staying open now but iv attached the edrp.log file anyway
[edrp.txt](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6695692/edrp.txt)

**Comment by VeeLume** [comment]
1. Did you have Discord running while you opend the app?
2. Which OS do you have?

**Comment by thenamesjay03** [comment]
1: i do have discord open if i dont i get failed to execute script BackgroundApp
2: windows 10
p.s. i moved the app folder from downloads to my programs folder and all i get is failed to execute script BackgroundApp no matter what now

**Comment by thenamesjay03** [comment]
when i redownloaded the app and leave it in the downloads folder it works

**Comment by VeeLume** [comment]
And it stops working when you move it?

**Comment by thenamesjay03** [comment]
yep

**Comment by thenamesjay03** [comment]
let me try and get a recording

**Comment by thenamesjay03** [comment]
sorry i cant get a recording

**Comment by VeeLume** [comment]
could you still upload the new log file?

**Comment by thenamesjay03** [comment]
ya sure

**Comment by thenamesjay03** [comment]
log file opening before moving app folder
[edrp.txt](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6695909/edrp.txt)

**Comment by thenamesjay03** [comment]
log file opening after moving app folder
[edrp.txt](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6695924/edrp.txt)

**Comment by VeeLume** [comment]
It looks like you didnt closed the tray app? The logfiles are the same just one is a bit longer. In the secone one the app gets closed at the end.

**Comment by thenamesjay03** [comment]
ah maby let me try closing the app did not noticed it did not closed

**Comment by thenamesjay03** [comment]
nope still not working

**Comment by VeeLume** [comment]
could you upload the new logfile when you start the app at the different location?

**Comment by thenamesjay03** [comment]
ok i found out what its doing my computer has 2 storage drives a hdd for my bulk storage and a ssd for system stuff that has about 40 gb free space on it if i move it from the downloads to the hdd it brakes it but if i move it from downloads to the system ssd drive it works fine

**Comment by VeeLume** [comment]
Oh good to know, let me try the same on my system

**Comment by VeeLume** [comment]
Okay i cant recreate it. So a log is probably the only way to find the issue.

**Comment by thenamesjay03** [comment]
ok well the file is currently on the working drive so im going to have to re move it

**Comment by VeeLume** [comment]
You could also just make a copy

**Comment by thenamesjay03** [comment]
[edrp.txt](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6696116/edrp.txt)

**Comment by VeeLume** [comment]
Hmm, no errors appears, but it looks like some files are still in downloads?
![image](https://user-images.githubusercontent.com/23563093/122968909-559a7480-d38c-11eb-8eb4-80667dd116a5.png)
Are you moving the whole folder or just the exe?

**Comment by thenamesjay03** [comment]
cut and past on the folder

**Comment by thenamesjay03** [comment]
i hate to give more bad news but its not updating the info
![Elite - Dangerous (CLIENT) 22_6_21 6_22_19 PM](https://user-images.githubusercontent.com/83084519/122971432-f38b4080-d386-11eb-8d72-68f2901a2072.png)
![🎨media - Discord 22_6_21 6_22_27 PM](https://user-images.githubusercontent.com/83084519/122971449-f84ff480-d386-11eb-9367-0ee3e8ea22ed.png)

**Comment by thenamesjay03** [comment]
I cant give any more info tonight my stepdad told me to come off my computer

**Comment by VeeLume** [comment]
So to summarize
- The app works if you keep it in the downloads directory
- The app works if you keep it on the C drive
- It stops working if you move it to the other drive

Are those statments correct?

Adding to this, currently all uploaded logfiles states that the exe is located at "...\Downloads\Elite Dangerous Rich Presence\Elite Dangerous Rich Presence.exe", which means i dont know what happens when you start it from another location. It would be great if you could take a fresh folder (freshly unzipped) and place it on the second drive where it presumably doesnt work. Just make sure you have at least the Elite Dangerous Launcher open, because the app closes itself immediatly if nothing from Elite is open.

**Comment by thenamesjay03** [comment]
yep those statements are correct. if it will help i will delete all working folders and make a fresh unzip to all 3 locations and upload the logs

**Comment by thenamesjay03** [comment]
Ok it dose not allow me to unzip directly to the C or D Drives. If i do i get failed to execute script BackgroundApp. The only way i can get the app to work is if i unzip it in downloads then move it to the working C Drive

**Comment by thenamesjay03** [comment]
i think im just a bug magnet

**Comment by VeeLume** [comment]
That sounds like maybe somthing went wrong while unzipping it. What program do you use to unzip?

**Comment by thenamesjay03** [comment]
Win rar

**Comment by VeeLume** [comment]
Hmm directly unzipping it to another drive with Win Rar works fine for me. Could you get the logfile when you got the "Failed to execute script BackgroundApp" crash?

**Comment by thenamesjay03** [comment]
It dosent make one

**Comment by VeeLume** [comment]
Hmm then something went seriously wrong.
Is threre a logging.yaml file?
Could you verify the SHA256 of the exe?
To do that you press win+r then type pwsh and press enter. Then type Get-FileHash and Drag & Drop the exe onto the window, so it should looks like this 
![image](https://user-images.githubusercontent.com/23563093/123296899-57447380-d517-11eb-8130-0226e1a0bb74.png)

The SHA256 is from the [newest release (V4.6 Small bug fix)](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/releases/tag/V4.6):
E4FAD7C6FE64D1E7AF4266EEAB2485B2A93AA31F277803E6347DC3986D4F90ED

The SHA256 from the [older release (V4.5 Odyssey Update)](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/releases/tag/V4.5):
64BFA27008F868CB72700AA02F006FCAE460E77CCADC2BD48C838E6BBE9EED69

Make sure you check against the right checksum!

**Comment by thenamesjay03** [comment]
[logging.txt](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6710770/logging.txt)

**Comment by thenamesjay03** [comment]
when i do windows r then type pwsh windows cant find it

**Comment by VeeLume** [comment]
Oh then just press win and search for Powershell

**Comment by thenamesjay03** [comment]
I get 64BFA27008F868CB72700AA02F006FCAE460E77CCADC2BD48C838E6BBE9EED69

**Comment by VeeLume** [comment]
Can you do the same with this version?
It keeps a window open which hopefully shows the error that you are encountering.
[Elite Dangerous Rich Presence.zip](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6710884/Elite.Dangerous.Rich.Presence.zip)

**Comment by thenamesjay03** [comment]
ok with this new version when i run it it opens a black box for a second then closes and this one dose make a log file

**Comment by thenamesjay03** [comment]
[edrp.txt](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6710997/edrp.txt)

**Comment by thenamesjay03** [comment]
the hash is 8687BE07942633C496F6599284EB9D031C9BD31420504F1B8AF6B4969421FB76

**Comment by VeeLume** [comment]
Hmm the window should be open for at least 30 sec. But the logfile doesnt show any problems it runs like normal. Could you try again with the elite launcher open and see if it crashes?

**Comment by thenamesjay03** [comment]
it is open

**Comment by thenamesjay03** [comment]
do you want me to try it in the downloads folder instead of the c drive

**Comment by VeeLume** [comment]
Run it on a location where the app doesnt worked

**Comment by thenamesjay03** [comment]
which one as there are 2 The D Drive or the C Drive directly unzipping

**Comment by VeeLume** [comment]
If it didnt worked on both then both would be great

**Comment by thenamesjay03** [comment]
well i sent the C Drive already so ill send along the d drive
and it works in the downlods still

**Comment by thenamesjay03** [comment]
[edrp.txt](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6711085/edrp.txt)

**Comment by thenamesjay03** [comment]
hash is 8687BE07942633C496F6599284EB9D031C9BD31420504F1B8AF6B4969421FB76

**Comment by VeeLume** [comment]
Hmm could you send me the window output? Just copy and paste.

**Comment by thenamesjay03** [comment]
if your referring to the black window it dose not stay up long for me to copy

**Comment by VeeLume** [comment]
Then im kinda clueless what exactly happens, as the app behaves way different than it should despite the fact that it is the same file.
Currently the only idea that i have left is to run the source directly without building an exe. But that would require a bit of a setup.
It works on the C drive right? Sorry to say that but the most simplest solution would be to just roll with it and keep it on C.

**Comment by thenamesjay03** [comment]
it works on the c drive along as i unzip it in downloads 1st
