### ISSUE TITLE
"Failed to execute script BackgroundApp" on title screen, and any time after initial load-in

### ISSUE THREAD

**Issue by Razwerkz** [Lasa2/ED-RichPresence#24]
EDRP crashes if the game is running, citing a problem with BackgroundApp.  The log says there was some sort of problem with "DistFromStarLS."
![unknown](https://user-images.githubusercontent.com/9700289/123176680-e8511700-d451-11eb-9132-db416c025b94.png)
`2021-06-23 18:26:15,555 - JournalFileApp - INFO - Reading <DirEntry 'Journal.210623175928.01.log'>
2021-06-23 18:26:16,979 - BackgroundApp - ERROR - Uncaught exception
Traceback (most recent call last):
  File "BackgroundApp.py", line 394, in <module>
  File "BackgroundApp.py", line 384, in run
  File "BackgroundApp.py", line 289, in event_processing
  File "BackgroundApp.py", line 135, in ev
KeyError: 'DistFromStarLS'`

[EDRP Log File](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6705180/edrp.log)
[EDRP Settings File (in TXT form)](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6705187/settings.yaml.txt)
[Active Journal](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/6705213/Journal.210623175928.01_.txt)

**Comment by VeeLume** [comment]
Fixed in the new [release](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/releases/tag/V4.6)

**Comment by Razwerkz** [comment]
Confirmed fixed for me.  Thanks!
