### ISSUE TITLE
I just can't make it work

### ISSUE THREAD

**Issue by rurv** [Lasa2/ED-RichPresence#27]
I've installed the latest and previous versions of the app. I've launched it multiple times, I have changed the logging level, i have fixed the journal path, but it still won't show any information on discord. I wanted to use this app because it's the only one that support odyssey that I could find. Please help me :)

**Comment by VeeLume** [comment]
Well you will need to provide more information on whats happening, if possible upload the edrp.log, the settings.yaml and the journal file that was active while the app run

**Comment by rurv** [comment]
When I'm running the app the task manager does tell me that it's running, but on Discord my activity isn't changing and is just showing the default Elite Dangerous status.

Files :
The edrp.log is empty, even after running the app. settings.yaml was converted to .txt because GitHub didn't let me upload it as .yaml
Journal file is the most recent file I could find, located in C:/User/Saved Games/Frontier Developments/Elite Dangerous/

[settings.txt](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/8766342/settings.txt)
[Journal.2022-05-24T173428.01.log](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/8766354/Journal.2022-05-24T173428.01.log)

**Comment by SmellyFishRW** [comment]
Same issue here. The rich presence doesn't change and remains as the default elite dangerous presence.
The program also does not close nor open by itself when elite is launched. Has to be opened manually.

**Comment by VeeLume** [comment]
Apparently with Odysee they changed the Journal file format which i didnt noticed. The latest version has this fixed
