### ISSUE TITLE
Crashes when encounters new journal name formatting

### ISSUE THREAD

**Issue by alex-f-k** [Lasa2/ED-RichPresence#28]
**Describe the bug**
ED changed formatting of logs from `YYmmDDHHMMSS.nn` to separated `YY-mm-DDTHHMMSS.nn`. Add support for the new formatting parsing.

**Comment by alex-f-k** [comment]
Should've checked open issues. #27 fails because of the new formatting as well. Journal file attached in the comment https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/issues/27#issuecomment-1136453487 has '-' separators for the date and 'T' separator between date and time.

**Comment by VeeLume** [comment]
Thank you for fixing my ugly code
