### ISSUE TITLE
Launch game with program

### ISSUE THREAD

**Issue by Dave247** [Lasa2/ED-RichPresence#3]
Unless I'm missing something, the correct usage is to launch the program after launching ED, as trying to launch it when the game isn't running will just result in it terminating itself.

I was thinking a suggestion could be to have it so on the first check after launching the program it could then launch the game itself, and that way be a true standalone experience.

Though then there would also be another thing to add and that is the implementation of if it should launch the Horizons or vanila game, but that shouldn't be as difficult to add on.

**Comment by VeeLume** [comment]
I implemented the function to start the Launcher at the first launch(the game itself didn't work) if the Game and Launcher isnt running.

**Comment by Dave247** [comment]
Thanks very much for that. I have idea for a further enhancement on top of this which I'll open as a separate issue.
