### ISSUE TITLE
Unhandled exception, crash on launch

### ISSUE THREAD

**Issue by Razwerkz** [Lasa2/ED-RichPresence#31]
When launching EDRP, after a few seconds, an "unhandled exception in script" error displays, before the program exits.

Log file is empty | [Settings file](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/11046042/settings.yaml.txt) | [Most recent journal file](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/11046043/Journal.2023-03-22T201950.01.log) | [The displayed error message](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/11046054/exception.txt)

**Comment by VeeLume** [comment]
Unfortunatly i cant reproduce that bug on my side, but it seems that issue is caused by kivy, the ui framework. I'm currently working on a new ui, without kivy, which is hopefully done in the next few weeks.
