### ISSUE TITLE
Fatal Error when trying to run the program automatically

### ISSUE THREAD

**Issue by Dave247** [Lasa2/ED-RichPresence#4]
In place of not having the program launch the game itself like in #3 , I have instead tried to do it the opposite way and have something else trigger it to launch when the game does.

I tried using [this method which works for EDMC](https://www.reddit.com/r/EliteDangerous/comments/9jjtab/psa_how_to_automatically_start_ed_market/) however adding the .exe as an action causes a fatal error where it fails to execute script gui, as seen in the below screenshot. 
![Elite_Dangerous_Rich_Presence_2019-11-10_13-33-04](https://user-images.githubusercontent.com/10183015/68537962-08d57600-03c1-11ea-8b76-2a3070774b55.png)

I also tried with the debug version but unfortunately as the program doesn't even manage to start no log file is created.

**Comment by VeeLume** [comment]
Closing this as #3 add a better way to start the game, because i think most people run a windows home edition

**Comment by Dave247** [comment]
I agree this method isn't really ideal even for EDMC, I do wish they had a way to automatically start it natively as well.
