### ISSUE TITLE
Error loading Python DLL when executing exe after build

### ISSUE THREAD

**Issue by The-Padi** [Lasa2/ED-RichPresence#45]
Hello, here is my problem.

If I try to execute the exe after build I get this error :

![image](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/assets/17253999/23c3f546-8c6b-47ed-ba62-9c0723186472)

Any idea why ?

**Comment by VeeLume** [comment]
After building you should have a dist folder with the builded app folder inside

**Comment by The-Padi** [comment]
Ok sorry, used to think that the build app would be in build ^^'

Works great !
