### ISSUE TITLE
Python Mk II support

### ISSUE THREAD

**Issue by raincentric** [Lasa2/ED-RichPresence#48]
Hello, just creating an enhancement request to have the Python Mk II supported. Thank you.

**Comment by VeeLume** [comment]
Could you go in a shipyard that sells a Python Mk II and then upload the Shipyard.json located under %USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous ?

**Comment by raincentric** [comment]
Verified it's listed in the json and attaching it to this reply, thank you. 
[Shipyard.json](https://github.com/user-attachments/files/15518087/Shipyard.json)

**Comment by VeeLume** [comment]
Fixed in the latest release
