### ISSUE TITLE
Minor UI Typo

### ISSUE THREAD

**Issue by Dave247** [Lasa2/ED-RichPresence#5]
When I was testing the program trying to get it to launch automatically, I happened to notice a small typo where there is a space missing for the Main menu status. Screenshot is attached below,
![DiscordCanary_2019-11-10_13-27-32](https://user-images.githubusercontent.com/10183015/68537985-987b2480-03c1-11ea-8709-70f79e71b1bb.png)

**Comment by VeeLume** [comment]
I fixed that in the code, so its in the next release.
