### ISSUE TITLE
Add launch arguments to path field

### ISSUE THREAD

**Issue by Dave247** [Lasa2/ED-RichPresence#6]
Following on from #3 , if possible you can add the ability for the program to recognise and parse on any arguments such as /EDH which would make the launcher default to Horizons. Though I admit I'm not sure if this would really be needed.

However a much greater use would enable the ability to launch the game through Steam, using the below target path [as written in this Reddit comment](https://www.reddit.com/r/EliteDangerous/comments/4620m9/did_the_latest_patch_break_launching_the_game/d02fk6t/).
`"C:\Program Files (x86)\Steam\Steam.exe" -applaunch 359320 /EDH /steamid 441340`

There is also another alternative which is to use `steam://rungameid/359320` which runs the launcher as if it was standalone, yet still being tied to Steam.

I tried using arguments in the existing version however I suspect the program was unable to read them as checking the log file showed that it was not able to detect the game path.

**Comment by VeeLume** [comment]
Now the program also takes arguments, but it defaults to just use the EDLauncher.exe because that way you don't need to start steam in the first place and it shows an option to launch Horizon(at least for me).

**Comment by Dave247** [comment]
You're right you don't need Steam, just call it personal preference on my part as it's just what I'm used to.

Anyway thanks for all the work on it, I can't think of anything else you to suggest to add to the program.
