### ISSUE TITLE
Program doesn't auto close when game & Launcher are closed

### ISSUE THREAD

**Issue by Dave247** [Lasa2/ED-RichPresence#7]
After the recent enchamcnet updates I've observed that the program no longer seems to terminate itself when both the game and launcher are closed. I've tested it both launching the game standalone and through Steam.

I changed the logging to debug but it doesn't log anything past the game path existing. The main thread won;t stop unless I manually close the program myself.

**Comment by VeeLume** [comment]
I fixed a bug caused by TypeErrors. New release is out.
