### ISSUE TITLE
Application crashes when you teleported to detention facility

### ISSUE THREAD

**Issue by Armankessilon** [Lasa2/ED-RichPresence#8]
Application crashes when you teleported to detention facility. And you need to restart the game completely to fix this.

**Comment by VeeLume** [comment]
Hmm i tested it on my side and it did not crash, so i need some files from you to look into it.

Can you send me the log file from the rich-presence(should be called ed-rp.log inside the folder)? And the journal file which crashed the rich-presence(located under C:\Users\"your username"\Saved Games\Frontier Developments\Elite Dangerous)?

**Comment by Armankessilon** [comment]
Sure. I am at work ATM but I will ask my friend to do it - he has the same problem. I will send it asap

**Comment by Armankessilon** [comment]
In the attachement: logs from application (but it seems to be useless), journals for today and yesterday (both had this problem).
I will discribe it more how it was today:
1. Getting wanted status.
2. Got killed - sent to detention facility (it is not necessary to get killed, you may also surrender to authorities when docked)
3. Got this message (see screenshot)
4. Application is not responding anymore in the tray - no context menu by right click. Also it stopped to change presence status.
5. Killing it via task manager
6. Running again - having the same error from the screenshot.

[ed_drp.zip]() (removed as this issue is closed and the logs contained the FID)

P.S. My friend has Russian client, I have English client. Also we've been sent to different detention facilities. Just for case if it helps

**Comment by VeeLume** [comment]
Fixed in the new release!
