### ISSUE TITLE
Suggestion to add ship type label below ship picture

### ISSUE THREAD

**Issue by Armankessilon** [Lasa2/ED-RichPresence#9]
Suggestion to add ship type label below ship picture. Sometimes it's not very clear to understand type of the ship just by its picture (for instance alliance ships). It would be nice to have a label too. And maybe a ship name at the tooltip

**Comment by VeeLume** [comment]
So there would be two ways:

Adding the small image with the Elite Logo and have the tooltip there
![image](https://user-images.githubusercontent.com/23563093/69035704-8c581e00-09e4-11ea-8eea-6d0912a4cca0.png)
or adding it to the large image tooltip
![image](https://user-images.githubusercontent.com/23563093/69036016-39329b00-09e5-11ea-878b-46931726f3c6.png)
Im not sure wich way looks nicer

**Comment by Armankessilon** [comment]
Is it possible to add just a title Anaconda below large logo? I think it would be nicer.
But by given options I would choose second option where we have a tooltip for big image

**Comment by VeeLume** [comment]
Added the second Option in the new release!
